name: aim/aim-cli packaging pipeline

on: workflow_dispatch

jobs:
  linux-dist:
    runs-on: ubuntu-latest
    name: Linux wheels build (using Docker)
    steps:
      - name: Install Docker & pull images
        run: |
          apt update && apt install -y docker.io
          sudo systemctl enable --now docker

          docker pull quay.io/pypa/manylinux_2_24_x86_64

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install dev dependencies
        run: |
          python -m pip install -r requirements.dev.txt

      - name: Build bdist wheels
        run: |
         docker run --mount type=bind,source=$PWD,target=/opt/aim quay.io/pypa/manylinux_2_24_x86_64 bash /opt/aim/docker/build-wheels.sh

      - name: Publish wheels
        env:
          PYPI_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          python -m pip install twine
          python -m twine upload -u __token__ -p "${PYPI_PASSWORD}" multilinux_dist/*

  macos-dist:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        os: [ 'macos-latest' ]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dev dependencies
        run: |
          python -m pip install -r requirements.dev.txt

      - name: Build bdist wheel
        run: |
          AIM_PKG_NAME=aim python setup.py bdist_wheel -d dist
          AIM_PKG_NAME=aim-cli python setup.py bdist_wheel -d dist

      - name: Build sdist
        if: matrix.python-version == '3.9'
        run: |
          AIM_PKG_NAME=aim python setup.py sdist
          AIM_PKG_NAME=aim-cli python setup.py sdist

      - name: Publish wheel
        env:
          PYPI_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          python -m pip install twine
          python -m twine upload -u __token__ -p "${PYPI_PASSWORD}" dist/*
